/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as FrontendRouteImport } from './routes/_frontend'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthRouteImport } from './routes/_auth'

const FrontendIndexLazyRouteImport = createFileRoute('/_frontend/')()
const DashboardMoviesLazyRouteImport = createFileRoute('/_dashboard/movies')()
const AuthSignUpLazyRouteImport = createFileRoute('/_auth/sign-up')()
const AuthLoginLazyRouteImport = createFileRoute('/_auth/login')()

const FrontendRoute = FrontendRouteImport.update({
  id: '/_frontend',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontendIndexLazyRoute = FrontendIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FrontendRoute,
} as any).lazy(() =>
  import('./routes/_frontend/index.lazy').then((d) => d.Route),
)
const DashboardMoviesLazyRoute = DashboardMoviesLazyRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/_dashboard/movies.lazy').then((d) => d.Route),
)
const AuthSignUpLazyRoute = AuthSignUpLazyRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/sign-up.lazy').then((d) => d.Route))
const AuthLoginLazyRoute = AuthLoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/login.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/login': typeof AuthLoginLazyRoute
  '/sign-up': typeof AuthSignUpLazyRoute
  '/movies': typeof DashboardMoviesLazyRoute
  '/': typeof FrontendIndexLazyRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginLazyRoute
  '/sign-up': typeof AuthSignUpLazyRoute
  '/movies': typeof DashboardMoviesLazyRoute
  '/': typeof FrontendIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_frontend': typeof FrontendRouteWithChildren
  '/_auth/login': typeof AuthLoginLazyRoute
  '/_auth/sign-up': typeof AuthSignUpLazyRoute
  '/_dashboard/movies': typeof DashboardMoviesLazyRoute
  '/_frontend/': typeof FrontendIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/sign-up' | '/movies' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/sign-up' | '/movies' | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/_dashboard'
    | '/_frontend'
    | '/_auth/login'
    | '/_auth/sign-up'
    | '/_dashboard/movies'
    | '/_frontend/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  FrontendRoute: typeof FrontendRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_frontend': {
      id: '/_frontend'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof FrontendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_frontend/': {
      id: '/_frontend/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof FrontendIndexLazyRouteImport
      parentRoute: typeof FrontendRoute
    }
    '/_dashboard/movies': {
      id: '/_dashboard/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof DashboardMoviesLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginLazyRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginLazyRoute: typeof AuthLoginLazyRoute
  AuthSignUpLazyRoute: typeof AuthSignUpLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginLazyRoute: AuthLoginLazyRoute,
  AuthSignUpLazyRoute: AuthSignUpLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardMoviesLazyRoute: typeof DashboardMoviesLazyRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardMoviesLazyRoute: DashboardMoviesLazyRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface FrontendRouteChildren {
  FrontendIndexLazyRoute: typeof FrontendIndexLazyRoute
}

const FrontendRouteChildren: FrontendRouteChildren = {
  FrontendIndexLazyRoute: FrontendIndexLazyRoute,
}

const FrontendRouteWithChildren = FrontendRoute._addFileChildren(
  FrontendRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  FrontendRoute: FrontendRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
